name: wad_interview_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_toggle_button: ^0.0.3
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.5.0+1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  copy_with_extension_gen: ^5.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf

    - family: Barlow
      fonts:
        - asset: fonts/barlow/Barlow-SemiBold.ttf
        - asset: fonts/barlow/Barlow-Medium.ttf
        - asset: fonts/barlow/Barlow-Light.ttf
        - asset: fonts/barlow/Barlow-Bold.ttf
